version: '3.8'

services:
  api_clientes:
    build:
      context: ./api_clientes
      dockerfile: Dockerfile
    container_name: api_clientes
    ports: 
      - "8000:8000"
    networks:
      app_network: 
        ipv4_address: 10.10.10.10
    depends_on:
      - db_clientes

  db_clientes:
    image: mysql:8
    container_name: db_clientes
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: clientes_user
      MYSQL_PASSWORD: clientesdb
    networks:
      app_network:
        ipv4_address: 10.10.10.11

  api_inventario:
    build:
      context: ./api_inventario
      dockerfile: Dockerfile
    container_name: api_inventario
    ports:
      - "8001:8001"
    networks: 
      app_network:
        ipv4_address: 10.10.10.20
    depends_on:
      - db_inventario

  db_inventario:
    image: mysql:8
    container_name: db_inventario
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario_db
      MYSQL_USER: inventario_user
      MYSQL_PASSWORD: inventariodb
    networks: 
      app_network:
        ipv4_address: 10.10.10.21

  api_relatorios:
    build:
      context: ./api_relatorios
      dockerfile: Dockerfile
    container_name: api_relatorios
    ports:
      - "8002:8002"
    networks:
      app_network:
        ipv4_address: 10.10.10.30
    depends_on:
      - db_relatorios

  db_relatorios:
    image: mysql:8
    container_name: db_relatorios
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: relatorios_db
      MYSQL_USER: relatorios_user
      MYSQL_PASSWORD: relatoriosdb
    networks: 
      app_network:
        ipv4_address: 10.10.10.31

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80"
    networks:
      - app_network
    depends_on:
      - api_clientes
      - api_inventario
      - api_relatorios

networks:
  app_network:
    driver: bridge
    ipam: 
      config:
        - subnet: 10.10.10.0/24
